
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TESIS = 5;
  public static final int PRINT_I = 18;
  public static final int PRINT_B = 19;
  public static final int CLOG = 35;
  public static final int PC = 3;
  public static final int INTERSEC = 24;
  public static final int DECL = 15;
  public static final int NOT = 11;
  public static final int AND = 9;
  public static final int IGUAL = 33;
  public static final int TYPE = 37;
  public static final int IN = 22;
  public static final int OR = 10;
  public static final int EMPTYSET = 38;
  public static final int DIV = 30;
  public static final int BEGIN = 6;
  public static final int IF = 12;
  public static final int EOF = 0;
  public static final int ASIG = 8;
  public static final int CARD = 25;
  public static final int error = 1;
  public static final int MUL = 29;
  public static final int COMA = 2;
  public static final int MENOS = 28;
  public static final int MENOR = 32;
  public static final int IDENT = 34;
  public static final int MAYOR = 31;
  public static final int OPUESTO = 39;
  public static final int BRAC = 20;
  public static final int UNION = 23;
  public static final int CINT = 36;
  public static final int WHILE = 16;
  public static final int THEN = 13;
  public static final int PROG = 14;
  public static final int LOWEST_ELEM = 26;
  public static final int END = 7;
  public static final int KET = 21;
  public static final int PAREN = 4;
  public static final int DO = 17;
  public static final int MAS = 27;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "COMA",
  "PC",
  "PAREN",
  "TESIS",
  "BEGIN",
  "END",
  "ASIG",
  "AND",
  "OR",
  "NOT",
  "IF",
  "THEN",
  "PROG",
  "DECL",
  "WHILE",
  "DO",
  "PRINT_I",
  "PRINT_B",
  "BRAC",
  "KET",
  "IN",
  "UNION",
  "INTERSEC",
  "CARD",
  "LOWEST_ELEM",
  "MAS",
  "MENOS",
  "MUL",
  "DIV",
  "MAYOR",
  "MENOR",
  "IGUAL",
  "IDENT",
  "CLOG",
  "CINT",
  "TYPE",
  "EMPTYSET",
  "OPUESTO"
  };
}

